### ISSUE TITLE
Need help to refactor example code

### ISSUE THREAD

**Issue by comtihon** [cyderize/rust-websocket#115]
Hi!
I am new to Rust, tried to re-organize code from your example and faced with some diffuculties:
I moved all handling code to handle_client. But I don't know connection type. What type I should use?
```
for connection in server.filter_map(Result::ok) {
        // Spawn a new thread for each connection.
        thread::spawn(move || {
            println!("thread started");
            handle_client(connection);
        });
    }
```
Second, I moved all message related code to handle_message, but again, have problems with types:
```
fn handle_message(sender: Sender, message: Message) {
    let message: Message = message.unwrap();
    match message.opcode {
        Type::Close => {
            let message = Message::close();
            sender.send_message(&message).unwrap();
            return;
        }
        Type::Ping => {
            let message = Message::pong(message.payload);
            sender.send_message(&message).unwrap();
        }
        _ => sender.send_message(&message).unwrap(),
    }
}
```
I have got following error when `use websocket::Sender;`:
```
fn handle_message(sender: Sender, message: Message) {
   | ^ the trait `websocket::Sender` cannot be made into an object
   |
   = note: method `send_dataframe` has generic type parameters
   = note: method `send_message` has generic type parameters
```
Will be thankfull for your help.

**Comment by illegalprime** [comment]
Hey @comtihon , `Sender` is a `trait`, so it represents any group of types. Because Rust is made to run without a runtime it needs to know the size (in memory) of all of the variables you use at compile time. `Sender` could be an `i32`, or it can be a `TcpStream` (for example), these two types take up different sizes in memory so you can't make a type that is either one and use it directly. You have to use `&Sender` (an immutable reference), `&mut Sender` (a mutable reference), `Box<Sender>` (a pointer to somewhere far away in memory), or similar since they all have known sizes.

To answer your actual question, you can see in the docs [here] that you called `.bind()` to create your server, which gave you a `Server<NoSslAcceptor>` that implements the `Iterator` trait giving items of type `AcceptResult<TcpStream>`. Then we use `.filter(Result::ok)` to only keep those connections in which the `AcceptResult` was `Ok` (so we only get the connections that are successful). this means for every run of the loop `connection` will have the type `WsUpgrade<TcpStream>`. Finally you have to call `.accept()` on the connection to accept it (you could deny it based on headers if you want). Which means that the type of the connection that you can use to send messages is `Client<TcpStream>`.

Here is a full example:
```rust
extern crate websocket;

use std::thread;
use std::net::TcpStream;
use websocket::{Server, Message, Client};
use websocket::message::Type;

fn main() {
    let server = Server::bind("127.0.0.1:2794").unwrap();

    for request in server.filter_map(Result::ok) {
        // Spawn a new thread for each connection.
        thread::spawn(move || {
            let mut client = request.accept().unwrap();
            let message = client.recv_message().unwrap();
            handle_message(client, message);
        });
    }
}

fn handle_message(mut sender: Client<TcpStream>, message: Message) {
    match message.opcode {
        Type::Close => {
            let message = Message::close();
            sender.send_message(&message).unwrap();
            return;
        },
        Type::Ping => {
            let message = Message::pong(message.payload);
            sender.send_message(&message).unwrap();
        },
        _ => sender.send_message(&message).unwrap(),
    }
}
```

**Comment by comtihon** [comment]
Thanks!
