### ISSUE TITLE
broken?

### ISSUE THREAD

**Issue by daogangtang** [cyderize/rust-websocket#12]
broken by library sha1?
how to fix?

**Comment by cyderize** [comment]
You can use the sha1 from my git repository by using the temp branch of rust-websocket.

In Cargo.toml:

```ini
[dependencies.websocket]
git = "https://github.com/cyderize/rust-websocket.git"
branch = "temp"
```

I opened a pull request a few days ago to the owner of rust-sha1, but they seem to be hard to contact at the moment.

**Comment by BenTheElder** [comment]
Unfortunately this leaves packages that depend on websocket unable to publish (to crates.io) in the meantime. Perhaps if the PR is not accepted within a reasonable timeline a fork could be published under an alternate name or something? Local/relative path vendorizing unfortunately seems prohibited by cargo for published packages; as well as git dependencies.

**Comment by cyderize** [comment]
Yeah, not having sha1 working is pretty much why I haven't been able to publish this version to crates.io.

I've decided to use [sha1-hasher](https://crates.io/crates/sha1-hasher) now, since it works - hopefully that should make it possible to continue using the library. That version is in the [sha1-hasher branch](https://github.com/cyderize/rust-websocket/tree/sha1-hasher) and is published as 0.9.6 on crates.io.

**Comment by BenTheElder** [comment]
Looks like a good solution. When you make the switch I'll finally move slack-rs to 1.0-alpha.

**Comment by cyderize** [comment]
The crates.io version should now be working, although you might want to wait a while before moving to 1.0-alpha. 

I've still got to deal with associated types, and there will likely be some large changes to the API (I might try to mirror the stream splitting from [RFC517](https://github.com/rust-lang/rfcs/pull/517) rather than having clones are Arcs everywhere).

**Comment by BenTheElder** [comment]
Ok. I've gone ahead and started updating because there is _so_ much that needs to be changed in my code to reach 1.0, but none of the calls to websocket need updating since the switch to websocket's hyper so far.

**Comment by cyderize** [comment]
I mean you may also need to change some of the websocket calls eventually as well - but they shouldn't be too major anyway (and I'll happily help out when I finish the changes).

**Comment by BenTheElder** [comment]
Ok, I'll continue to track crates.io 's latest as much as possible. Thanks.

**Comment by BenTheElder** [comment]
So i've updated to 0.9.6, and updated my demo project, and while i'm not 100% certain it isn't my fault i'm getting `ResponseError("Sec-WebSocket-Accept is invalid")` when connecting to slack. I'm going to do some more debugging and report back.

**Comment by BenTheElder** [comment]
Well disabling the call to check `res.validate(&key)` after connecting seems to leave everything else functioning as expected, so I'd say there's a bug somewhere between slack and rust-websocket.

**Comment by cyderize** [comment]
Yes, there seems to be a problem with validation - I neglected a lot of client-side testing, and this doesn't appear to work. I'll have a closer look at it.

**Comment by BenTheElder** [comment]
Ok, thanks.

**Comment by cyderize** [comment]
I think I've fixed the issue in 0.9.7.

**Comment by BenTheElder** [comment]
I've re-enabled validation after switching to 0.9.7 and it seems to be working as expected.

**Comment by cyderize** [comment]
I've now removed the dependency on a separate SHA-1 crate, since OpenSSL can already do SHA-1 (and much faster than any Rust crates).

Version 0.10.0 introduces a different API, so see the examples in `examples/client.rs` and `examples/server.rs`.

I've removed the clone() and Mutex stuff, instead using a `split()` method to allow sending and receiving from different threads.

If you still need to be able to `clone()`, you'll have to put the use an `Arc<Mutex<Client>>`.
