### ISSUE TITLE
Sender shared across threads

### ISSUE THREAD

**Issue by FreeFull** [cyderize/rust-websocket#14]
Is it possible to have multiple threads use a Sender simultaneously?
I have a thread whose entire purpose is sending a ping-type message, and it worked with the old Client design, but I'm not sure how to transition it into the new Receiver/Sender design (Sender doesn't implement Clone).

**Comment by cyderize** [comment]
You'll have to do some `Arc<Mutex<...>>` stuff now - which I removed from websocket since it was a burden on maintenance and also carried a performance penalty (so now it's up to the user to do this).

So if you only need to send from multiple threads, just wrap up the Sender into an `Arc<Mutex<Sender>>`.

```rust
let (sender, mut receiver) = response.begin().split();	
let sendable_sender = Arc::new(Mutex::new(sender));
	
let sender_1 = sendable_sender.clone();
let sender_2 = sendable_sender.clone();
	
Thread::spawn(move || {
	let sender = sender_1;
	for message in receiver.incoming_messages() {
		let received = message.unwrap();
		println!("Recv: {:?}", received);

		let message = Message::Text("Hello from thread 1!".to_string());
		let mut sender_guard = sender.lock().unwrap();
		sender_guard.send_message(message).unwrap();
	}
});
Thread::spawn(move || {
	let sender = sender_2;
	loop {
		let message = Message::Text("Hello from thread 2".to_string());
		let mut sender_guard = sender.lock().unwrap();
		sender_guard.send_message(message).unwrap();
		sleep(Duration::seconds(1));
	}
});
```

The alternative (and I tend to prefer this) is to have a thread for sending messages in a loop and a channel for telling it to send a message.

```rust
let (mut sender, mut receiver) = response.begin().split();	
let (tx, rx) = channel();

let tx_1 = tx.clone();
let tx_2 = tx.clone();

Thread::spawn(move || {
	loop {
		// Send loop
		let message = rx.recv().unwrap();
		sender.send_message(message).unwrap();
	}
});

Thread::spawn(move || {
	loop {
		// Keep sending pongs
		tx_1.send(Message::Text("Ping".to_string())).unwrap();
		sleep(Duration::seconds(10));
	}
});

// Receive loop
for message in receiver.incoming_messages() {
	// Echo received messages
	tx_2.send(message.unwrap()).unwrap();
}
```

**Comment by BenTheElder** [comment]
What would be a sane way to close the message thread loop(s) from main?

I've been playing around with that in slack-rs and so far my best solution so far is to construct the websocket from a TcpStream I own (then wrapped in an SslStream, and used to build the Client/Request), clone the stream, pass the original with websocket into a worker thread and then call close_read and close_write on the stream from the top level thread when I need to exit...

I'm getting an unknown error afterward the thread that owns all of the child threads closes the stream, waits on the children then exits, however it's possible this may be related to the calling code, which is in a dynamically reloaded library (which is technically very unsafe in rust).

Is there a better way to go about this? Perhaps sending a close message could tell rust-websocket to tear down the stream?

**Comment by cyderize** [comment]
If should be possible to just call something like `receiver.get_mut().close_read()` and `receiver.get_mut().close_write()` assuming you have access to the receiver in the main thread (or alternatively `sender.get_mut().close_read()` and `sender.get_mut().close_write()` to close using the sender).

Since the underlying stream for the Receiver and Sender is the entire TcpStream, you can close the stream from either one.

**Comment by BenTheElder** [comment]
Ok. I'll continue doing that then.

**Comment by cyderize** [comment]
Note that now `examples/client.rs` contains a better example of how a client could be implemented.

**Comment by illegalprime** [comment]
Should this issue be closed?

**Comment by illegalprime** [comment]
closing
