### ISSUE TITLE
Library doesn't seem to expose whether the WebSocket Connection is Closed *cleanly*

### ISSUE THREAD

**Issue by Ms2ger** [cyderize/rust-websocket#47]
Or the documentation doesn't say.

**Comment by cyderize** [comment]
As far as I can tell, according to the [spec](https://tools.ietf.org/html/rfc6455#section-7.1.4), the only difference between a clean close and an unclean close is whether the closing handshake is performed, and since the closing handshake is done by the user, it should be possible to check that this was done before the connection was closed.

Is there something in servo that relies on knowing whether the connection was closed cleanly?

**Comment by illegalprime** [comment]
closing for now, @Ms2ger let me know if you have any more information on this.
