### ISSUE TITLE
Explicit versions for dependencies

### ISSUE THREAD

**Issue by badboy** [cyderize/rust-websocket#55]
As seen in #54 star-dependencies can cause problems for packages relying on websocket.
Also it's very unlikely that websocket will work with whatever versions its dependencies decide to release.

Would you consider adding explicit version requirements? I could send a PR for that.

**Comment by illegalprime** [comment]
Completely agree. Especially since there's breaking API changes all the time with `openssl`. A PR would be wonderful! I haven't had time to give this lib more attention. Please see if you can target the most recent version of `openssl`.

@cyderize `openssl` has to be locked to `^0.6.0` and published as soon as possible so at least for now no one will experience a broken library.

**Comment by illegalprime** [comment]
The Rust team is on top of it:
["In 1.6 it will no longer be possible to publish crates with wildcard dependencies."](https://github.com/rust-lang/rust/blob/stable/RELEASES.md#version-150-2015-12-10)
